apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: linkerd
  namespace: linkerd
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: linkerd.geek.per.sg
    http:
      paths:
      - path: /
        backend:
          serviceName: linkerd-web
          servicePort: 8084

