kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: gJgoU2zLRx+BoWERPMfoTukCnk/CXf/4Onl8z0BHExg=
      - identity: {}