apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    name: kubernetes-dashboard
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090